apiVersion: v2
publisher: coenraads
name: bracket pair
version: 0.0.28
type: VS Code extension
displayName: Bracket Pair
title: Project Initializer by Red Hat
description: A lightweight extension based on Red Hat launcher to generate quickstart
  projects using Eclipse Che
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/fabric8-launcher/launcher-vscode-extension
category: Other
firstPublicationDate: '2019-04-18'
spec:
  extensions:
  - https://github.com/benoitf/my-plugin-registry/raw/master/coenraads/bracket-pair-colorizer/1.0.61/bracket-pair-colorizer-1.0.61.vsix
